apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: rajavinodh96/counter-app:latest 
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://admin1:password@docdb.cluster-cn8w62sg28p9.us-west-2.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
        envFrom:
        - secretRef:
            name: mongodb-credentials
        volumeMounts:
        - name: tls-bundle
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls-bundle
        configMap:
          name: tls-ca-bundle

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

